---
## Bagian G — Diterapkan pada proyek tim (dikerjakan di luar kelas)

Bagian ini adalah isi **M1**. Kerjakan bersama tim pada dataset proyek Anda sendiri.

In [1]:
import pandas as pd
import numpy as np
import hashlib, os

pd.set_option('display.max_columns', 100)
pd.set_option('display.width', 1000)
print('pandas', pd.__version__)

pandas 2.2.3

### G1 — Pertanyaan analisis
Tulis **3–5 pertanyaan** yang lolos tiga uji. Untuk setiap pertanyaan, sebutkan kolom yang akan dipakai.

**Pertanyaan Payung:**

Bagaimana kebiasaan penggunaan ponsel sebelum tidur (bedtime phone habits) berkaitan dengan durasi tidur dan tingkat sleep debt pengguna?

**Pertanyaan Turunan:**

Bagaimana perbedaan rata-rata bedtime_phone_minutes pada setiap kelompok sleep_debt_category? (Kolom: bedtime_phone_minutes, sleep_debt_category)
Kelompok occupation_type mana yang memiliki rata-rata bedtime_phone_minutes tertinggi dan total_sleep_hours terendah? (Kolom: occupation_type, bedtime_phone_minutes, total_sleep_hours)
Kategori primary_bedtime_app apa yang paling berkaitan dengan tingginya bedtime_phone_minutes sebelum tidur? (Kolom: primary_bedtime_app, bedtime_phone_minutes)

### G2 — Provenans data
Catat lima butir berikut di README repositori tim:

| Butir | Isi |
|---|---|
| Nama sumber | Kaggle.com|
| Tautan atau nama instansi |https://www.kaggle.com/datasets/samartalwar/sleep-debt-and-screen-time-late-night-phone-habits |
| Tanggal pengambilan | 28 September 2026 |
| Lisensi atau nomor surat izin | CC BY-SA 4.0|
| Kalimat sitasi untuk laporan | |

### G3 — Kamus data
Isi `TEMPLATE_Kamus_Data.csv` untuk **setiap** kolom dataset tim, termasuk kolom `kategori_data_pribadi` dan `tindakan_penanganan`. Simpan sebagai `data_dictionary.md` atau `.csv` di repositori.

In [ ]:
# G4 — jalankan penanganan pada data tim dan periksa nilai k
# Salin pola Bagian E dan F, ganti dataset dan nama kolomnya.
# Simpan hasilnya ke data/processed/ dan JANGAN unggah data/raw/

In [2]:
FILE = 'bedtime_screentime_sleep_debt.csv'

if not os.path.exists(FILE):
    try:
        from google.colab import files
        files.upload()          # pilih bedtime_screentime_sleep_debt.csv
    except ImportError:
        raise FileNotFoundError('Letakkan CSV di folder yang sama dengan notebook ini.')

df = pd.read_csv(FILE)
print(df.shape)
df.head(10)

Saving bedtime_screentime_sleep_debt.csv to bedtime_screentime_sleep_debt.csv
(8500, 18)

     user_id  age      gender            occupation_type    chronotype  bedtime_phone_minutes       primary_bedtime_app  screen_brightness_pct  blue_light_filter_active  caffeine_post_5pm_mg  physical_activity_min  sleep_latency_min  total_sleep_hours  deep_sleep_pct  rem_sleep_pct  morning_alarm_snoozes  next_day_fatigue_score sleep_debt_category
0  USR-00001   29      Female  Healthcare / Shift Worker  Intermediate                    179        Instagram / Reddit                     54                         1                     0                     21               84.4               3.20            23.5           22.2                      7                    10.0   Severe Sleep Debt
1  USR-00002   58      Female                    Student  Intermediate                    163                   YouTube                     76                         1                    92                     72               86.7               4.06            18.0           21.5                      7                    10.0   Severe Sleep Debt
2  USR-00003   41      Female  Healthcare / Shift Worker     Night Owl                    100            TikTok / Reels                     59                         0                    45                     23               70.5               3.20            18.1           20.5                      7                    10.0   Severe Sleep Debt
3  USR-00004   36  Non-Binary                Remote Tech  Intermediate                     34                   YouTube                     52                         0                    97                     49               38.1               6.99            21.6           22.4                      1                     1.7        Mild Deficit
4  USR-00005   23      Female  Healthcare / Shift Worker  Intermediate                     27            TikTok / Reels                     82                         1                     0                     38               32.3               4.58            24.1           22.8                      4                     5.3       Moderate Debt
5  USR-00006   23        Male  Healthcare / Shift Worker  Intermediate                     76            TikTok / Reels                     39                         0                   136                     42               50.6               5.87            21.4           17.5                      4                     5.0       Moderate Debt
6  USR-00007   20      Female                Remote Tech     Night Owl                     53            TikTok / Reels                     32                         0                     0                     64               36.2               4.43            22.7           19.0                      6                     6.4       Moderate Debt
7  USR-00008   49        Male                Remote Tech  Morning Lark                    113                   YouTube                     34                         1                    39                     58               60.2               5.94            19.3           19.9                      3                     4.5       Moderate Debt
8  USR-00009   36        Male       Freelance / Creative  Morning Lark                     65            News / Reading                     35                         1                     0                     25               28.2               8.00            22.2           18.5                      1                     1.0    Optimal Recovery
9  USR-00010   40      Female                    Student     Night Owl                     70  Streaming (Netflix/Hulu)                     63                         1                   115                     59               53.7               4.70            23.5           16.6                      4                     7.3       Moderate Debt

In [3]:
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8500 entries, 0 to 8499
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   user_id                   8500 non-null   object
 1   age                       8500 non-null   int64
 2   gender                    8500 non-null   object
 3   occupation_type           8500 non-null   object
 4   chronotype                8500 non-null   object
 5   bedtime_phone_minutes     8500 non-null   int64
 6   primary_bedtime_app       8500 non-null   object
 7   screen_brightness_pct     8500 non-null   int64
 8   blue_light_filter_active  8500 non-null   int64
 9   caffeine_post_5pm_mg      8500 non-null   int64
 10  physical_activity_min     8500 non-null   int64
 11  sleep_latency_min         8500 non-null   float64
 12  total_sleep_hours         8500 non-null   float64
 13  deep_sleep_pct            8500 non-null   float64
 14  rem_sleep_pct             8500 non-null   float64
 15  morning_alarm_snoozes     8500 non-null   int64
 16  next_day_fatigue_score    8500 non-null   float64
 17  sleep_debt_category       8500 non-null   object
dtypes: float64(5), int64(7), object(6)
memory usage: 1.2+ MB

(8500, 18)

In [5]:
import os, shutil

# 1. Buat struktur folder
os.makedirs('data/raw', exist_ok=True)
os.makedirs('data/processed', exist_ok=True)

# 3. Baca dari raw
df = pd.read_csv('data/raw/bedtime_screentime_sleep_debt.csv')

In [6]:
# 4. Jalankan pola E1, E2, E4 (hapus, hash, generalisasi) — sesuaikan dengan PENANDAAN kolom sleep

PENANDAAN_SLEEP = {
    # --- Pengenal langsung (direct identifier) ---
    'user_id':         ('pengenal langsung', 'hash'),

    # --- Kuasi-identifier ---
    'age':             ('kuasi-identifier', 'generalisasi'),
    'gender':          ('kuasi-identifier', 'pertahankan'),
    'occupation_type': ('kuasi-identifier', 'pertahankan'),

    # --- Bukan data pribadi (perilaku, bukan identitas) ---
    'chronotype':      ('bukan data pribadi', 'pertahankan'),
}

# Bangun DataFrame dari seluruh kolom df
tanda_sleep = pd.DataFrame({
    'nama_kolom': df.columns
})

def ambil_kategori(nama):
    return PENANDAAN_SLEEP.get(nama, ('bukan data pribadi', 'pertahankan'))[0]

def ambil_tindakan(nama):
    return PENANDAAN_SLEEP.get(nama, ('bukan data pribadi', 'pertahankan'))[1]

tanda_sleep['kategori'] = tanda_sleep['nama_kolom'].apply(ambil_kategori)
tanda_sleep['tindakan'] = tanda_sleep['nama_kolom'].apply(ambil_tindakan)

print(tanda_sleep['kategori'].value_counts())
tanda_sleep

kategori
bukan data pribadi    14
kuasi-identifier       3
pengenal langsung      1
Name: count, dtype: int64

                  nama_kolom            kategori      tindakan
0                    user_id   pengenal langsung          hash
1                        age    kuasi-identifier  generalisasi
2                     gender    kuasi-identifier   pertahankan
3            occupation_type    kuasi-identifier   pertahankan
4                 chronotype  bukan data pribadi   pertahankan
5      bedtime_phone_minutes  bukan data pribadi   pertahankan
6        primary_bedtime_app  bukan data pribadi   pertahankan
7      screen_brightness_pct  bukan data pribadi   pertahankan
8   blue_light_filter_active  bukan data pribadi   pertahankan
9       caffeine_post_5pm_mg  bukan data pribadi   pertahankan
10     physical_activity_min  bukan data pribadi   pertahankan
11         sleep_latency_min  bukan data pribadi   pertahankan
12         total_sleep_hours  bukan data pribadi   pertahankan
13            deep_sleep_pct  bukan data pribadi   pertahankan
14             rem_sleep_pct  bukan data pribadi   pertahankan
15     morning_alarm_snoozes  bukan data pribadi   pertahankan
16    next_day_fatigue_score  bukan data pribadi   pertahankan
17       sleep_debt_category  bukan data pribadi   pertahankan

In [7]:
kolom_dihapus = [kolom for kolom, (kategori, tindakan) in PENANDAAN_SLEEP.items() if tindakan == 'hapus']

# aman_sleep = df, MINUS kolom-kolom yang harus dihapus
aman_sleep = df.drop(columns=kolom_dihapus)

print("Kolom dibuang :", len(kolom_dihapus), "→", kolom_dihapus)
print("Kolom tersisa :", aman_sleep.shape[1], "dari", df.shape[1])

aman_sleep.head()

Kolom dibuang : 0 → []
Kolom tersisa : 18 dari 18

     user_id  age      gender            occupation_type    chronotype  bedtime_phone_minutes primary_bedtime_app  screen_brightness_pct  blue_light_filter_active  caffeine_post_5pm_mg  physical_activity_min  sleep_latency_min  total_sleep_hours  deep_sleep_pct  rem_sleep_pct  morning_alarm_snoozes  next_day_fatigue_score sleep_debt_category
0  USR-00001   29      Female  Healthcare / Shift Worker  Intermediate                    179  Instagram / Reddit                     54                         1                     0                     21               84.4               3.20            23.5           22.2                      7                    10.0   Severe Sleep Debt
1  USR-00002   58      Female                    Student  Intermediate                    163             YouTube                     76                         1                    92                     72               86.7               4.06            18.0           21.5                      7                    10.0   Severe Sleep Debt
2  USR-00003   41      Female  Healthcare / Shift Worker     Night Owl                    100      TikTok / Reels                     59                         0                    45                     23               70.5               3.20            18.1           20.5                      7                    10.0   Severe Sleep Debt
3  USR-00004   36  Non-Binary                Remote Tech  Intermediate                     34             YouTube                     52                         0                    97                     49               38.1               6.99            21.6           22.4                      1                     1.7        Mild Deficit
4  USR-00005   23      Female  Healthcare / Shift Worker  Intermediate                     27      TikTok / Reels                     82                         1                     0                     38               32.3               4.58            24.1           22.8                      4                     5.3       Moderate Debt

In [8]:
# Hash
GARAM = 'ganti-dengan-kalimat-rahasia-tim'
import hashlib

def samarkan(nilai, garam):
    if pd.isna(nilai):
        return np.nan
    else:
        return hashlib.sha256(garam.encode() + str(nilai).encode()).hexdigest()[:12]

print(samarkan('USR-00001', GARAM))

437fb72df714

In [9]:
# TODO E3 — buktikan hash bersifat konsisten dan tidak terbaca
# a. Hash dua kali nilai yang sama, tunjukkan hasilnya identik
print(samarkan('USR-00001', GARAM))
print(samarkan('USR-00001', GARAM))
# b. Hash dua nilai berbeda, tunjukkan hasilnya berbeda
print("Nilai yang berbeda")
print(samarkan('USR-00003', GARAM))
print(samarkan('USR-00004', GARAM))

437fb72df714
437fb72df714
Nilai yang berbeda
f685ed043ba8
87ebed7e40b2

In [10]:
# --- E4: GENERALISASI ---
batas_umur = [18, 25, 35, 45, 55, 66]
label_umur = ['18-24', '25-34', '35-44', '45-54', '55-65']
aman_sleep['kelompok_umur'] = pd.cut(df['age'], bins=batas_umur, labels=label_umur, right=False)
aman_sleep = aman_sleep.drop(columns=['age'], errors='ignore')

print("\nE4 — Distribusi kelompok umur:")
print(aman_sleep['kelompok_umur'].value_counts().sort_index())

aman_sleep.head()

E4 — Distribusi kelompok umur:
kelompok_umur
18-24    1915
25-34    2940
35-44    1948
45-54    1043
55-65     654
Name: count, dtype: int64

     user_id      gender            occupation_type    chronotype  bedtime_phone_minutes primary_bedtime_app  screen_brightness_pct  blue_light_filter_active  caffeine_post_5pm_mg  physical_activity_min  sleep_latency_min  total_sleep_hours  deep_sleep_pct  rem_sleep_pct  morning_alarm_snoozes  next_day_fatigue_score sleep_debt_category kelompok_umur
0  USR-00001      Female  Healthcare / Shift Worker  Intermediate                    179  Instagram / Reddit                     54                         1                     0                     21               84.4               3.20            23.5           22.2                      7                    10.0   Severe Sleep Debt         25-34
1  USR-00002      Female                    Student  Intermediate                    163             YouTube                     76                         1                    92                     72               86.7               4.06            18.0           21.5                      7                    10.0   Severe Sleep Debt         55-65
2  USR-00003      Female  Healthcare / Shift Worker     Night Owl                    100      TikTok / Reels                     59                         0                    45                     23               70.5               3.20            18.1           20.5                      7                    10.0   Severe Sleep Debt         35-44
3  USR-00004  Non-Binary                Remote Tech  Intermediate                     34             YouTube                     52                         0                    97                     49               38.1               6.99            21.6           22.4                      1                     1.7        Mild Deficit         35-44
4  USR-00005      Female  Healthcare / Shift Worker  Intermediate                     27      TikTok / Reels                     82                         1                     0                     38               32.3               4.58            24.1           22.8                      4                     5.3       Moderate Debt         18-24

In [11]:
# 5. Jalankan pola F1-F5 (ukur k) — pakai fungsi cek_k yang sudah ada

def cek_k(data, kolom):
    ukuran_grup = data.groupby(kolom, observed=True).size()
    k = ukuran_grup.min()
    grup_berisi_1 = (ukuran_grup == 1).sum()
    total_grup = ukuran_grup.shape[0]
    return pd.Series({'k': k, 'grup_berisi_1': grup_berisi_1, 'total_grup': total_grup})

In [12]:
# F2 — sebelum penanganan (pakai df_sleep asli)
kolom_qi_sebelum = ['age', 'gender', 'occupation_type', 'chronotype']
hasil_sebelum_sleep = cek_k(df, kolom_qi_sebelum)
print("F2 — Sebelum:")
print(hasil_sebelum_sleep)

# F3 — sesudah generalisasi
kolom_qi_sesudah = ['kelompok_umur', 'gender', 'occupation_type', 'chronotype']
hasil_sesudah_sleep = cek_k(aman_sleep, kolom_qi_sesudah)
print("\nF3 — Sesudah:")
print(hasil_sesudah_sleep)

F2 — Sebelum:
k                   1
grup_berisi_1     297
total_grup       1517
dtype: int64

F3 — Sesudah:
k                  1
grup_berisi_1     13
total_grup       214
dtype: int64

In [13]:
print("Status k saat ini:", hasil_sesudah_sleep['k'])

if hasil_sesudah_sleep['k'] < 5:
    # Cek kombinasi mana yang masih berisiko
    ukuran_grup = aman_sleep.groupby(kolom_qi_sesudah, observed=True).size().reset_index(name='jumlah')
    berisiko = ukuran_grup[ukuran_grup['jumlah'] < 5].sort_values('jumlah')
    print("Kombinasi berisiko (<5):")
    print(berisiko.head(10))

    # Coba lebarkan kelompok umur jadi 3 kategori
    batas_lebar = [9, 25, 80]
    label_lebar = ['10 - 25', '25+']
    aman_sleep['kelompok_umur_v2'] = pd.cut(df['age'], bins=batas_lebar, labels=label_lebar, right=False)

    hasil_v2 = cek_k(aman_sleep, ['kelompok_umur_v2', 'gender', 'occupation_type', 'chronotype'])
    print("\nPercobaan — umur dilebarkan jadi 3 kelompok:")
    print(hasil_v2)

    if hasil_v2['k'] < 5:
        # Coba keluarkan chronotype dari daftar quasi-identifier
        hasil_v3 = cek_k(aman_sleep, ['kelompok_umur_v2', 'gender', 'occupation_type'])
        print("\nPercobaan — tanpa chronotype:")
        print(hasil_v3)

Status k saat ini: 1
Kombinasi berisiko (<5):
    kelompok_umur      gender            occupation_type    chronotype  jumlah
34          18-24  Non-Binary       Freelance / Creative  Morning Lark       1
81          25-34  Non-Binary  Healthcare / Shift Worker  Morning Lark       1
79          25-34  Non-Binary       Freelance / Creative     Night Owl       1
167         45-54  Non-Binary       Freelance / Creative  Morning Lark       1
129         35-44  Non-Binary                Remote Tech  Morning Lark       1
132         35-44  Non-Binary                    Student  Morning Lark       1
123         35-44  Non-Binary       Freelance / Creative  Morning Lark       1
124         35-44  Non-Binary       Freelance / Creative     Night Owl       1
166         45-54  Non-Binary           Corporate 9-to-5     Night Owl       1
213         55-65  Non-Binary                    Student     Night Owl       1

Percobaan — umur dilebarkan jadi 3 kelompok:
k                 1
grup_berisi_1     1
total_grup       90
dtype: int64

Percobaan — tanpa chronotype:
k                 5
grup_berisi_1     0
total_grup       30
dtype: int64

In [14]:
tabel_silang_sleep = pd.crosstab(aman_sleep['kelompok_umur'], aman_sleep['occupation_type'])
print("Tabel silang kelompok_umur x occupation_type:")
print(tabel_silang_sleep)

sel_kecil_sleep = (tabel_silang_sleep > 0) & (tabel_silang_sleep < 5)
jumlah_sel_kecil_sleep = sel_kecil_sleep.sum().sum()
print(f"\nJumlah sel terisi tapi < 5 peserta: {jumlah_sel_kecil_sleep}")

Tabel silang kelompok_umur x occupation_type:
occupation_type  Corporate 9-to-5  Freelance / Creative  Healthcare / Shift Worker  Remote Tech  Student
kelompok_umur
18-24                         638                   205                        235          474      363
25-34                        1003                   302                        335          755      545
35-44                         664                   191                        228          452      413
45-54                         333                   126                        110          289      185
55-65                         200                    77                         89          172      116

Jumlah sel terisi tapi < 5 peserta: 0

In [19]:
aman_sleep.to_csv('data/processed/sleep_data_aman.csv', index=False)
print("Tersimpan di data/processed/sleep_data_aman.csv")

# Verifikasi
print("\nIsi data/raw/:", os.listdir('data/raw'))
print("Isi data/processed/:", os.listdir('data/processed'))

Tersimpan di data/processed/sleep_data_aman.csv

Isi data/raw/: ['bedtime_screentime_sleep_debt.csv']
Isi data/processed/: ['sleep_data_aman.csv']

In [16]:
print(df['occupation_type'].value_counts())
print(df['gender'].value_counts())

occupation_type
Corporate 9-to-5             2838
Remote Tech                  2142
Student                      1622
Healthcare / Shift Worker     997
Freelance / Creative          901
Name: count, dtype: int64
gender
Female        4347
Male          3905
Non-Binary     248
Name: count, dtype: int64

In [17]:
print(df.columns.tolist())

['user_id', 'age', 'gender', 'occupation_type', 'chronotype', 'bedtime_phone_minutes', 'primary_bedtime_app', 'screen_brightness_pct', 'blue_light_filter_active', 'caffeine_post_5pm_mg', 'physical_activity_min', 'sleep_latency_min', 'total_sleep_hours', 'deep_sleep_pct', 'rem_sleep_pct', 'morning_alarm_snoozes', 'next_day_fatigue_score', 'sleep_debt_category']

In [18]:
df.shape

(8500, 18)